#!/bin/bash
DISPLAY_RE="([0-9]+)x([0-9]+)\\+([0-9]+)\\+([0-9]+)"
IMAGE_RE="([0-9]+)x([0-9]+)"
FOLDER=`dirname "$BASH_SOURCE"`
TEXT="$FOLDER/text.png"
PARAMS=""
OUTPUT_IMAGE="/tmp/i3lock.png"
PROCESSING_IMAGE="/tmp/i3lock_proc.png"
MONITOR_COUNT=0

#Make custom lockscreen image using $I3LOCK_BACKGROUND screen size :
while read LINE
do
  #If we are reading the line that contains the position information:
  if [[ $LINE =~ $DISPLAY_RE ]]; then
    #Extract information and append some parameters to the ones that will be given to ImageMagick:
    WIDTH=${BASH_REMATCH[1]}
    HEIGHT=${BASH_REMATCH[2]}
    X=${BASH_REMATCH[3]}
    Y=${BASH_REMATCH[4]}
    MONITOR_COUNT=$((MONITOR_COUNT+1))
    if [[ "$MONITOR_COUNT" == "1" ]]; then
	    eval convert $I3LOCK_BACKGROUND -resize ${WIDTH}x${HEIGHT}! $OUTPUT_IMAGE
    else
            OUTPUT_IMAGE_INFO=`identify $OUTPUT_IMAGE`
	    [[ $OUTPUT_IMAGE_INFO =~ $IMAGE_RE ]]
	    OUTPUT_IMAGE_WIDTH=${BASH_REMATCH[1]}
	    OUTPUT_IMAGE_HEIGHT=${BASH_REMATCH[2]}
	    eval convert $OUTPUT_IMAGE -extent $((OUTPUT_IMAGE_WIDTH+WIDTH))x$HEIGHT $OUTPUT_IMAGE
            eval convert $I3LOCK_BACKGROUND -resize ${WIDTH}X${HEIGHT}! $PROCESSING_IMAGE
            eval convert $OUTPUT_IMAGE $PROCESSING_IMAGE -geometry +$X+$Y -composite $OUTPUT_IMAGE
    fi;
  fi
done <<<"`xrandr`"

#Get dimensions of the text image:
TEXT_IMAGE_INFO=`identify $TEXT`
[[ $TEXT_IMAGE_INFO =~ $IMAGE_RE ]]
TEXT_WIDTH=${BASH_REMATCH[1]}
TEXT_HEIGHT=${BASH_REMATCH[2]}

#Execute xrandr to get information about the monitors:
while read LINE
do
  #If we are reading the line that contains the position information:
  if [[ $LINE =~ $DISPLAY_RE ]]; then
    #Extract information and append some parameters to the ones that will be given to ImageMagick:
    WIDTH=${BASH_REMATCH[1]}
    HEIGHT=${BASH_REMATCH[2]}
    X=${BASH_REMATCH[3]}
    Y=${BASH_REMATCH[4]}
    TEXT_X=$(($X+$WIDTH/2-$TEXT_WIDTH/2))
    TEXT_Y=$(($Y+$HEIGHT/2-$TEXT_HEIGHT/2+200))

    PARAMS="$PARAMS '$TEXT' '-geometry' '+$TEXT_X+$TEXT_Y' '-composite'"
  fi
done <<<"`xrandr`"

#Execute ImageMagick:
PARAMS="'$OUTPUT_IMAGE' '-level' '0%,100%,0.6' $PARAMS '$OUTPUT_IMAGE'"
eval convert $PARAMS

#Lock the screen:
i3lock -i $OUTPUT_IMAGE -t

#Remove the generated image:
rm $OUTPUT_IMAGE
rm $PROCESSING_IMAGE
